apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: vsphere-csi.community.tanzu.vmware.com.2.4.1
spec:
  refName: vsphere-csi.community.tanzu.vmware.com
  version: 2.4.1
  releaseNotes: "vsphere-csi 2.4.1-rc.1 https://github.com/kubernetes-sigs/vsphere-csi-driver/releases/tag/v2.4.1-rc.1"
  licenses:
    - "Apache 2.0"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: projects.registry.vmware.com/tce/vsphere-csi@sha256:8809f8abc06877e803f56b05a83b3e27c0dbac1e5f50a5c9b6c6bf9744c02fe0
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
