apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: antrea.community.tanzu.vmware.com.0.13.3
spec:
  refName: antrea.community.tanzu.vmware.com
  version: 0.13.3
  releaseNotes: "antrea 0.13.3 https://github.com/antrea-io/antrea/releases/tag/v0.13.3"
  licenses:
    - "Apache 2.0"
  template:
    spec:
      syncPeriod: 5m
      fetch:
        - imgpkgBundle:
            image: projects.registry.vmware.com/tce/antrea@sha256:14294c577af686c721468d797248118bd771a15787a4294efd26dbe72240d348
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
      - kapp:
          rawOptions:
            - --wait-timeout=30s
