#@data/values
---

namespace: kube-system
infraProvider: vsphere
nodeSelector: null
ipFamily: null
calico:
  config:
    clusterCIDR: null
    #! "0" as default means MTU will be auto detected
    vethMTU: "0"
