apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: pinniped.community.tanzu.vmware.com.0.4.4
spec:
  refName: pinniped.community.tanzu.vmware.com
  version: 0.4.4
  releaseNotes: "pinniped 0.4.4 https://github.com/vmware-tanzu/pinniped/releases/tag/v0.4.4"
  licenses:
    - "Apache 2.0"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: projects.registry.vmware.com/tce/pinniped@sha256:54fd56a1843cd9ce58647c63d01a9c4b46e2b183d0d66d1cc36b5a91edfc202e
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - kbld-config.yaml
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
