apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: vsphere-cpi.community.tanzu.vmware.com.1.21.0
spec:
  refName: vsphere-cpi.community.tanzu.vmware.com
  version: 1.21.0
  releaseNotes: "vsphere-cpi 1.21.0 https://github.com/kubernetes/cloud-provider-vsphere"
  licenses:
    - "Apache 2.0"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: projects.registry.vmware.com/tce/vsphere-cpi@sha256:2918ec5e2610be6801fb38db4a0f0f5e7bb537a6b07260d6b295e2315224540a
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
