apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: ako-operator.community.tanzu.vmware.com.1.5.0
  namespace: ako-operator
spec:
  refName: ako-operator.community.tanzu.vmware.com
  version: 1.5.0
  releaseNotes: "ako-operator 1.5.0"
  licenses:
    - "UNKNOWN"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: projects.registry.vmware.com/tce/ako-operator@sha256:ebe610f9df2df64b4a18481cabf1b85b44a969dd8b2af5ea1f513ffdb34c8654
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
