apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: load-balancer-and-ingress-service.community.tanzu.vmware.com.1.6.1
  namespace: load-balancer-and-ingress-service
spec:
  refName: load-balancer-and-ingress-service.community.tanzu.vmware.com
  version: 1.6.1
  releaseNotes: "load-balancer-and-ingress-service 1.6.1"
  licenses:
    - "UNKNOWN"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: projects.registry.vmware.com/tce/load-balancer-and-ingress-service@sha256:a15c498ab6320cb1c2403a453b45a1401e3d86f34d76bc4f14cec3c2434dd4b5
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
