apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: kapp-controller.community.tanzu.vmware.com.0.34.0
spec:
  refName: kapp-controller.community.tanzu.vmware.com
  version: 0.35.0
  releaseNotes: "kapp-controller 0.35.0 https://github.com/vmware-tanzu/carvel-kapp-controller"
  licenses:
    - "Apache 2.0"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: projects.registry.vmware.com/tce/kapp-controller@sha256:6649d06214b2527d47c9b1d146799841656988c682ae7ec46ec4d0edb37c56fa
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
