apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: kapp-controller.community.tanzu.vmware.com.0.33.1
spec:
  refName: kapp-controller.community.tanzu.vmware.com
  version: 0.33.1
  releaseNotes: "kapp-controller 0.33.1 https://github.com/vmware-tanzu/carvel-kapp-controller"
  licenses:
    - "Apache 2.0"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: projects.registry.vmware.com/tce/kapp-controller@sha256:58849bfe4ec31d510135f3ea057c34201c7eb9c769a915e6fc57f27ae9e3e818
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
