apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: kapp-controller.community.tanzu.vmware.com.0.30.0
spec:
  refName: kapp-controller.community.tanzu.vmware.com
  version: 0.30.0
  releaseNotes: "kapp-controller 0.30.0 https://github.com/vmware-tanzu/carvel-kapp-controller"
  licenses:
    - "Apache 2.0"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: projects.registry.vmware.com/tce/kapp-controller@sha256:6fa7447e9886f5af7cca18ad21ccef608c121c54c58fd196fb129cd2a8adddce
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
