apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: metrics-server.community.tanzu.vmware.com.0.5.1
spec:
  refName: metrics-server.community.tanzu.vmware.com
  version: 0.5.1
  releaseNotes: "metrics-server 0.5.1 https://github.com/kubernetes-sigs/metrics-server/releases/tag/v0.5.1"
  licenses:
    - "Apache 2.0"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: projects.registry.vmware.com/tce/metrics-server@sha256:8e2e69ca8f4904967a11e06aa182192f57645b284c854f38a139fe92b2916e89
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
