apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: vsphere-csi.community.tanzu.vmware.com.2.4.0
spec:
  refName: vsphere-csi.community.tanzu.vmware.com
  version: 2.4.0
  releaseNotes: "vsphere-csi 2.4.0 https://github.com/kubernetes-sigs/vsphere-csi-driver/releases/tag/v2.4.0"
  licenses:
    - "Apache 2.0"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: projects.registry.vmware.com/tce/vsphere-csi@sha256:34098c5e175b73e119d1ebeb34a7277125bafb5094f9decc891eb0af66ac9c4e
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
